### ISSUE TITLE
Specify a kind for reals

### ISSUE THREAD

**Issue by Beliavsky** [urbanjost/M_datapac#2]
The code use default reals. Does SPAG have an option to replace

`real x`

with 

`real(kind=wp) x`

and to add 

`use kind_mod, only: wp`

within each procedure?

**Comment by urbanjost** [comment]
Unfortunately I no longer have access to the SPAG tools. I hope to make such a change so as to be able to generate at least 32-bit and 64-bit versions though. I want to get the documentation and unit tests completed first; especially unit tests so I can verify
I do not inadvertently change results while continuing the modernization. It should be relatively straight-forward to make the basic change, leaving it single-precision for now.

**Comment by urbanjost** [comment]
There were values already designated as double precision; but all other values now have the kind "wp" specified. Some of the constants probably need specified with more precision to use anything other than single; but many of the routines do not contain constants, or only values with a file digits (1.0, 0.5, 2.0,...).  Changed intrinsics to be generic names as well, so should at least build and run with "wp" being changed; but there is some need to go in and change the number of digits in some of the fixed values, including Pi.

**Comment by urbanjost** [comment]
It builds a single and double module  and creates generics so it would work with real32 or real64.
